# Generated by Django 5.1.3 on 2025-02-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='gen',
        ),
    ]
