# Generated by Django 5.2a1 on 2025-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0004_remove_test_image_remove_test_image_data_test_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(null=True)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
