# Generated by Django 5.2a1 on 2025-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0005_slate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
