# Generated by Django 5.2a1 on 2025-02-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0006_alter_slate_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gen',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
