# Generated by Django 5.2a1 on 2025-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0007_delete_gen_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
