# Generated by Django 5.2a1 on 2025-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0009_alter_audiofile_audio_alter_slate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
