# Generated by Django 5.2a1 on 2025-02-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chromesthesia', '0010_slate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slate',
            name='name',
        ),
    ]
